### PR TITLE
Use copy of x0 in scipy.optimize.newton to prevent side effect

### PR DESCRIPTION
**Pull request by maierbn**
This fixes the linked issue.

### CODE REVIEW

**Comment by johannes-mueller** [comment]
Is the new test actually sensitive for the change? I reverted the production code changes locally and the new test still passes.

**Comment by johannes-mueller** [comment]
Or maybe Windows <> Linux? 

So it does fail on your system without the changes?

**Comment by maierbn** [comment]
No, the issue does not occur for me in the test. But when do basically the same in a different package that imports pylife (but in python 3.13), the issue occurs. Is it required to have a test for this PR to be mergable?

**Comment by johannes-mueller** [comment]
Ah ok. There is actually a lot more issues with python 3.13 that I intent to address. Maybe check this workflow here

https://github.com/boschresearch/pylife/actions/runs/11832914483/job/32970554847

Maybe we should do that in one PR and at the same time add a python-3.13 test in the usual test suite.

**Comment by johannes-mueller** [comment]
Took this over to #139 to make it Python 3.13 compliant. As it turns out according to our tests `copy.copy()` is not necessary. `np.asarray()` seems to suffice.

If you have a case in which we really need to copy, please provide a test that demonstrates it and add it to #139 or in a later PR. In case we really need to copy `numpy` or `pandas` datastructures I would be inclined to use their `.copy()` methods rather than `copy.copy()`.

**Comment by maierbn** [comment]
I checked again in my setup (python 3.13, numpy 2) and `np.asarray` fixes the problem.

**Pull request closed without merging**
